# Generated by Django 4.2.2 on 2023-06-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clockin',
            name='status',
            field=models.CharField(choices=[('IN', 'Clocked In'), ('OUT', 'Clocked Out'), ('BREAK', 'On Meal Break')], default='OUT', max_length=5),
        ),
    ]
