# Generated by Django 4.2.2 on 2023-06-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian_app', '0003_clockin_job_costs_clockin_job_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
