# Generated by Django 4.2.2 on 2023-06-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian_app', '0004_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
