# Generated by Django 4.2.2 on 2023-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meridian_app', '0005_contact_delete_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='meal_break_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
